# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTable',
            fields=[
                ('queryid', models.TextField(primary_key=True, serialize=False)),
                ('mappcount', models.IntegerField()),
                ('unmappcount', models.IntegerField()),
                ('domain', models.TextField()),
                ('phylum', models.TextField()),
                ('taxoclass', models.TextField()),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('domainCount', models.IntegerField()),
                ('phylumCount', models.IntegerField()),
                ('taxoclassCount', models.IntegerField()),
                ('orderCount', models.IntegerField()),
                ('familyCount', models.IntegerField()),
                ('genusCount', models.IntegerField()),
                ('speciesCount', models.IntegerField()),
                ('domainSensitivity', models.FloatField()),
                ('phylumSensitivity', models.FloatField()),
                ('taxoclassSensitivity', models.FloatField()),
                ('orderSensitivity', models.FloatField()),
                ('familySensitivity', models.FloatField()),
                ('genusSensitivity', models.FloatField()),
                ('speciesSensitivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTable',
            fields=[
                ('refernceid', models.TextField(primary_key=True, serialize=False)),
                ('domain', models.TextField()),
                ('phylum', models.TextField()),
                ('taxoclass', models.TextField()),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
            ],
        ),
    ]
